

name: 'energy_dbt'
version: '1.0.0'

profile: 'energy_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:        
  - "target"
  - "dbt_packages"


models:
  energy_dbt:
        +materialized: table


seeds:
  energy_pipeline:  
    municipality_region_mapping:    
      +materialized: seed